name: tdil-platform
services:
- name: api
  source_dir: /
  github:
    repo: pelenupe/tdil-prod
    branch: main
    deploy_on_push: true
  build_command: |
    # Install backend dependencies only
    npm ci
    
    # Create basic frontend for now
    mkdir -p public
    cat > public/index.html << 'EOF'
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>tDIL Platform</title>
        <style>
            body { font-family: Arial, sans-serif; max-width: 800px; margin: 50px auto; padding: 20px; text-align: center; }
            .container { background: #f5f5f5; padding: 30px; border-radius: 10px; }
            h1 { color: #333; }
            .api-info { background: white; padding: 20px; margin: 20px 0; border-radius: 5px; }
            a { color: #007bff; text-decoration: none; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🎓 tDIL Platform API</h1>
            <p>The backend API is running successfully!</p>
            
            <div class="api-info">
                <h3>API Endpoints Available:</h3>
                <p><strong>Health Check:</strong> <a href="/health">/health</a></p>
                <p><strong>Authentication:</strong> /api/auth/register, /api/auth/login</p>
                <p><strong>Users:</strong> /api/users/profile</p>
                <p><strong>Events:</strong> /api/events</p>
                <p><strong>Jobs:</strong> /api/jobs</p>
                <p><strong>Points:</strong> /api/points</p>
                <p><strong>Rewards:</strong> /api/rewards</p>
            </div>
            
            <p><em>Frontend interface coming soon...</em></p>
        </div>
    </body>
    </html>
    EOF
    
    echo "Basic frontend created, backend ready to deploy"
  run_command: node server.js
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 5001
  routes:
  - path: /api
  - path: /
  health_check:
    http_path: /health
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "5001"
  - key: DATABASE_URL
    value: ${db.DATABASE_URL}
  - key: JWT_SECRET
    value: "WnPQXSHGXjN2+YsQNP6+lC4fHmxDM3snEAbCfzNLA9Y="
    type: SECRET
  - key: JWT_EXPIRES_IN
    value: "15m"
  - key: JWT_REFRESH_EXPIRES_IN
    value: "7d"
  - key: FRONTEND_URL
    value: "${APP_URL}"
  - key: RATE_LIMIT_WINDOW_MS
    value: "900000"
  - key: RATE_LIMIT_MAX_REQUESTS
    value: "50"
  - key: HELMET_ENABLED
    value: "true"
  - key: COMPRESSION_ENABLED
    value: "true"
  - key: TRUST_PROXY
    value: "true"

databases:
- name: db
  engine: PG
  version: "15"
  size: basic
