name: tdil-platform
services:
- name: api
  source_dir: /
  github:
    repo: pelenupe/tdil-final
    branch: main
    deploy_on_push: true
  build_command: |
    npm ci
    cd tdil-frontend && npm ci && npm run build
    cp -r tdil-frontend/dist/* public/
  run_command: node server.js
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 5001
  routes:
  - path: /api
  - path: /
  health_check:
    http_path: /health
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "5001"
  - key: JWT_SECRET
    value: "your-super-secure-jwt-secret-key-change-this-256-bit-random"
    type: SECRET
  - key: JWT_EXPIRES_IN
    value: "15m"
  - key: JWT_REFRESH_EXPIRES_IN
    value: "7d"
  - key: FRONTEND_URL
    value: "${APP_URL}"
  - key: RATE_LIMIT_WINDOW_MS
    value: "900000"
  - key: RATE_LIMIT_MAX_REQUESTS
    value: "50"
  - key: HELMET_ENABLED
    value: "true"
  - key: COMPRESSION_ENABLED
    value: "true"
  - key: TRUST_PROXY
    value: "true"

databases:
- name: tdil-db
  engine: PG
  version: "13"
  size: basic

jobs:
- name: db-migrate
  source_dir: /
  github:
    repo: pelenupe/tdil-final
    branch: main
  build_command: npm ci
  run_command: npm run migrate
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  kind: PRE_DEPLOY
  envs:
  - key: NODE_ENV
    value: production
