name: tdil-platform
services:
- name: api
  source_dir: /
  github:
    repo: pelenupe/tdil-prod
    branch: main
    deploy_on_push: true
  build_command: |
    npm ci --include=dev
    cd tdil-frontend
    npm ci --include=dev
    npm run build
    cd ..
    mkdir -p public
    if [ -d "tdil-frontend/dist" ]; then
      cp -r tdil-frontend/dist/* public/
    else
      echo "Frontend dist directory not found, creating basic index.html"
      echo '<html><body><h1>tDIL Platform Loading...</h1></body></html>' > public/index.html
    fi
  run_command: node server.js
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 5001
  routes:
  - path: /api
  - path: /
  health_check:
    http_path: /health
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "5001"
  - key: DATABASE_URL
    value: ${db.DATABASE_URL}
  - key: JWT_SECRET
    value: "WnPQXSHGXjN2+YsQNP6+lC4fHmxDM3snEAbCfzNLA9Y="
    type: SECRET
  - key: JWT_EXPIRES_IN
    value: "15m"
  - key: JWT_REFRESH_EXPIRES_IN
    value: "7d"
  - key: FRONTEND_URL
    value: "${APP_URL}"
  - key: RATE_LIMIT_WINDOW_MS
    value: "900000"
  - key: RATE_LIMIT_MAX_REQUESTS
    value: "50"
  - key: HELMET_ENABLED
    value: "true"
  - key: COMPRESSION_ENABLED
    value: "true"
  - key: TRUST_PROXY
    value: "true"

databases:
- name: db
  engine: PG
  version: "15"
  size: basic
